name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to Hugging Face Spaces
        run: |
          git push --force https://${{ secrets.HF }}@huggingface.co/spaces/WaqasAkram041/demo2.git main
